### ISSUE TITLE
route config

### ISSUE THREAD

**Issue by hkremer** [ervaude/json_example#7]
Hi, I am trying to implement the api in typo3 v9

Until now I was not able to get a right route config for the api

Can you help?

This is my config:
```
routeEnhancers:
  ApiPages:
    type: Extbase
    limitToPages: [48]
    extension: eo_pages
    plugin: api_page
    routes:
      -
        routePath: '/pageapi'
        _controller: 'Api::list'
      -
        routePath: '/pageapi/{page}'
        _controller: 'Api::show'
        _arguments:
          page: 'page'
    defaultController: 'Api::show'
    requirements:
      page: '\d+'

```
